<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260106164740 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE agency_statistics (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date DATE NOT NULL, total_listings INT DEFAULT 0 NOT NULL, active_listings INT DEFAULT 0 NOT NULL, total_views INT DEFAULT 0 NOT NULL, total_contacts INT DEFAULT 0 NOT NULL, avg_listing_price NUMERIC(12, 2) DEFAULT 0 NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, agency_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2F2EFE80CDEADB2A ON agency_statistics (agency_id)');
        $this->addSql('CREATE UNIQUE INDEX unique_agency_date ON agency_statistics (agency_id, date)');
        $this->addSql('CREATE TABLE email_templates (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, template_key VARCHAR(100) NOT NULL, subject VARCHAR(255) NOT NULL, body_html TEXT NOT NULL, body_text TEXT DEFAULT NULL, variables JSON DEFAULT NULL, is_active BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_6023E2A524FB228B ON email_templates (template_key)');
        $this->addSql('CREATE TABLE favorites (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, notes TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, property_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E46960F5A76ED395 ON favorites (user_id)');
        $this->addSql('CREATE INDEX IDX_E46960F5549213EC ON favorites (property_id)');
        $this->addSql('CREATE UNIQUE INDEX unique_favorite ON favorites (user_id, property_id)');
        $this->addSql('CREATE TABLE flagged_content (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, target_id INT NOT NULL, reason VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, status VARCHAR(255) DEFAULT \'pending\' NOT NULL, reviewed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, reporter_id INT DEFAULT NULL, reviewed_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3E919834E1CFE6F5 ON flagged_content (reporter_id)');
        $this->addSql('CREATE INDEX IDX_3E919834FC6B21F1 ON flagged_content (reviewed_by_id)');
        $this->addSql('CREATE TABLE messages (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, subject VARCHAR(255) DEFAULT NULL, message TEXT NOT NULL, is_read BOOLEAN DEFAULT false NOT NULL, read_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, sender_id INT NOT NULL, receiver_id INT NOT NULL, property_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_DB021E96F624B39D ON messages (sender_id)');
        $this->addSql('CREATE INDEX IDX_DB021E96CD53EDB6 ON messages (receiver_id)');
        $this->addSql('CREATE INDEX IDX_DB021E96549213EC ON messages (property_id)');
        $this->addSql('CREATE TABLE moderation_actions (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, target_id INT NOT NULL, action VARCHAR(255) NOT NULL, reason TEXT DEFAULT NULL, notes TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, moderator_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2E0B3A70D0AFA354 ON moderation_actions (moderator_id)');
        $this->addSql('CREATE TABLE property_contacts (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, phone VARCHAR(20) DEFAULT NULL, message TEXT NOT NULL, contact_type VARCHAR(255) DEFAULT \'info_request\' NOT NULL, status VARCHAR(255) DEFAULT \'new\' NOT NULL, response_notes TEXT DEFAULT NULL, responded_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, property_id INT NOT NULL, user_id INT DEFAULT NULL, responded_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6DC72137549213EC ON property_contacts (property_id)');
        $this->addSql('CREATE INDEX IDX_6DC72137A76ED395 ON property_contacts (user_id)');
        $this->addSql('CREATE INDEX IDX_6DC72137296135A7 ON property_contacts (responded_by_id)');
        $this->addSql('CREATE TABLE property_media (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, media_type VARCHAR(255) NOT NULL, url VARCHAR(500) NOT NULL, thumbnail_url VARCHAR(500) DEFAULT NULL, position INT DEFAULT 0 NOT NULL, caption VARCHAR(255) DEFAULT NULL, is_main BOOLEAN DEFAULT false NOT NULL, storage_path VARCHAR(500) DEFAULT NULL, file_size INT DEFAULT NULL, mime_type VARCHAR(100) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, property_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_AC3F6001549213EC ON property_media (property_id)');
        $this->addSql('CREATE TABLE property_views (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ip_address VARCHAR(45) DEFAULT NULL, user_agent TEXT DEFAULT NULL, view_date DATE NOT NULL, view_time TIME(0) WITHOUT TIME ZONE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, property_id INT NOT NULL, user_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D7E35D8A549213EC ON property_views (property_id)');
        $this->addSql('CREATE INDEX IDX_D7E35D8AA76ED395 ON property_views (user_id)');
        $this->addSql('CREATE TABLE saved_searches (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) DEFAULT NULL, filters JSON NOT NULL, notification_frequency VARCHAR(255) DEFAULT \'daily\' NOT NULL, last_notified_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_EF93F31A76ED395 ON saved_searches (user_id)');
        $this->addSql('CREATE TABLE site_settings (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, setting_key VARCHAR(100) NOT NULL, setting_value TEXT DEFAULT NULL, setting_type VARCHAR(255) DEFAULT \'string\' NOT NULL, category VARCHAR(50) DEFAULT NULL, description TEXT DEFAULT NULL, is_public BOOLEAN DEFAULT false NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E9081F1F5FA1E697 ON site_settings (setting_key)');
        $this->addSql('ALTER TABLE agency_statistics ADD CONSTRAINT FK_2F2EFE80CDEADB2A FOREIGN KEY (agency_id) REFERENCES agencies (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE favorites ADD CONSTRAINT FK_E46960F5A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE favorites ADD CONSTRAINT FK_E46960F5549213EC FOREIGN KEY (property_id) REFERENCES properties (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE flagged_content ADD CONSTRAINT FK_3E919834E1CFE6F5 FOREIGN KEY (reporter_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE flagged_content ADD CONSTRAINT FK_3E919834FC6B21F1 FOREIGN KEY (reviewed_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE messages ADD CONSTRAINT FK_DB021E96F624B39D FOREIGN KEY (sender_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE messages ADD CONSTRAINT FK_DB021E96CD53EDB6 FOREIGN KEY (receiver_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE messages ADD CONSTRAINT FK_DB021E96549213EC FOREIGN KEY (property_id) REFERENCES properties (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE moderation_actions ADD CONSTRAINT FK_2E0B3A70D0AFA354 FOREIGN KEY (moderator_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE property_contacts ADD CONSTRAINT FK_6DC72137549213EC FOREIGN KEY (property_id) REFERENCES properties (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE property_contacts ADD CONSTRAINT FK_6DC72137A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE property_contacts ADD CONSTRAINT FK_6DC72137296135A7 FOREIGN KEY (responded_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE property_media ADD CONSTRAINT FK_AC3F6001549213EC FOREIGN KEY (property_id) REFERENCES properties (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE property_views ADD CONSTRAINT FK_D7E35D8A549213EC FOREIGN KEY (property_id) REFERENCES properties (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE property_views ADD CONSTRAINT FK_D7E35D8AA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE saved_searches ADD CONSTRAINT FK_EF93F31A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE agency_statistics DROP CONSTRAINT FK_2F2EFE80CDEADB2A');
        $this->addSql('ALTER TABLE favorites DROP CONSTRAINT FK_E46960F5A76ED395');
        $this->addSql('ALTER TABLE favorites DROP CONSTRAINT FK_E46960F5549213EC');
        $this->addSql('ALTER TABLE flagged_content DROP CONSTRAINT FK_3E919834E1CFE6F5');
        $this->addSql('ALTER TABLE flagged_content DROP CONSTRAINT FK_3E919834FC6B21F1');
        $this->addSql('ALTER TABLE messages DROP CONSTRAINT FK_DB021E96F624B39D');
        $this->addSql('ALTER TABLE messages DROP CONSTRAINT FK_DB021E96CD53EDB6');
        $this->addSql('ALTER TABLE messages DROP CONSTRAINT FK_DB021E96549213EC');
        $this->addSql('ALTER TABLE moderation_actions DROP CONSTRAINT FK_2E0B3A70D0AFA354');
        $this->addSql('ALTER TABLE property_contacts DROP CONSTRAINT FK_6DC72137549213EC');
        $this->addSql('ALTER TABLE property_contacts DROP CONSTRAINT FK_6DC72137A76ED395');
        $this->addSql('ALTER TABLE property_contacts DROP CONSTRAINT FK_6DC72137296135A7');
        $this->addSql('ALTER TABLE property_media DROP CONSTRAINT FK_AC3F6001549213EC');
        $this->addSql('ALTER TABLE property_views DROP CONSTRAINT FK_D7E35D8A549213EC');
        $this->addSql('ALTER TABLE property_views DROP CONSTRAINT FK_D7E35D8AA76ED395');
        $this->addSql('ALTER TABLE saved_searches DROP CONSTRAINT FK_EF93F31A76ED395');
        $this->addSql('DROP TABLE agency_statistics');
        $this->addSql('DROP TABLE email_templates');
        $this->addSql('DROP TABLE favorites');
        $this->addSql('DROP TABLE flagged_content');
        $this->addSql('DROP TABLE messages');
        $this->addSql('DROP TABLE moderation_actions');
        $this->addSql('DROP TABLE property_contacts');
        $this->addSql('DROP TABLE property_media');
        $this->addSql('DROP TABLE property_views');
        $this->addSql('DROP TABLE saved_searches');
        $this->addSql('DROP TABLE site_settings');
    }
}
