<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260106083802 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE agencies (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, name_ar VARCHAR(255) DEFAULT NULL, rc_number VARCHAR(50) DEFAULT NULL, ice_number VARCHAR(15) DEFAULT NULL, patent_number VARCHAR(50) DEFAULT NULL, address TEXT DEFAULT NULL, address_ar TEXT DEFAULT NULL, city VARCHAR(100) DEFAULT NULL, city_ar VARCHAR(100) DEFAULT NULL, postal_code VARCHAR(10) DEFAULT NULL, country VARCHAR(100) NOT NULL, description TEXT DEFAULT NULL, description_ar TEXT DEFAULT NULL, logo VARCHAR(500) DEFAULT NULL, website VARCHAR(500) DEFAULT NULL, facebook VARCHAR(500) DEFAULT NULL, instagram VARCHAR(500) DEFAULT NULL, verification_status VARCHAR(255) NOT NULL, verification_document VARCHAR(500) DEFAULT NULL, agency_type VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE agencies');
    }
}
