<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260106143207 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE agency_agents (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, role VARCHAR(255) NOT NULL, is_primary_contact BOOLEAN DEFAULT false NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, agency_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_494E6A2ECDEADB2A ON agency_agents (agency_id)');
        $this->addSql('CREATE INDEX IDX_494E6A2EA76ED395 ON agency_agents (user_id)');
        $this->addSql('ALTER TABLE agency_agents ADD CONSTRAINT FK_494E6A2ECDEADB2A FOREIGN KEY (agency_id) REFERENCES agencies (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE agency_agents ADD CONSTRAINT FK_494E6A2EA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE agency_agent DROP CONSTRAINT fk_284713b3cdeadb2a');
        $this->addSql('ALTER TABLE agency_agent DROP CONSTRAINT fk_284713b367b3b43d');
        $this->addSql('DROP TABLE agency_agent');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE agency_agent (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, is_primary_contact BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, agency_id INT NOT NULL, users_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_284713b367b3b43d ON agency_agent (users_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_284713b3cdeadb2a ON agency_agent (agency_id)');
        $this->addSql('ALTER TABLE agency_agent ADD CONSTRAINT fk_284713b3cdeadb2a FOREIGN KEY (agency_id) REFERENCES agencies (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE agency_agent ADD CONSTRAINT fk_284713b367b3b43d FOREIGN KEY (users_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE agency_agents DROP CONSTRAINT FK_494E6A2ECDEADB2A');
        $this->addSql('ALTER TABLE agency_agents DROP CONSTRAINT FK_494E6A2EA76ED395');
        $this->addSql('DROP TABLE agency_agents');
    }
}
