<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260106142844 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE agency_agent (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, is_primary_contact BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, agency_id INT NOT NULL, users_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_284713B3CDEADB2A ON agency_agent (agency_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_284713B367B3B43D ON agency_agent (users_id)');
        $this->addSql('ALTER TABLE agency_agent ADD CONSTRAINT FK_284713B3CDEADB2A FOREIGN KEY (agency_id) REFERENCES agencies (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE agency_agent ADD CONSTRAINT FK_284713B367B3B43D FOREIGN KEY (users_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE agency_agent DROP CONSTRAINT FK_284713B3CDEADB2A');
        $this->addSql('ALTER TABLE agency_agent DROP CONSTRAINT FK_284713B367B3B43D');
        $this->addSql('DROP TABLE agency_agent');
    }
}
