<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260106154144 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE agency_subscriptions (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(255) NOT NULL, billing_period VARCHAR(255) NOT NULL, current_period_start TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, current_period_end TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, auto_renew BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, agency_id INT NOT NULL, plan_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4FCF00D0CDEADB2A ON agency_subscriptions (agency_id)');
        $this->addSql('CREATE INDEX IDX_4FCF00D0E899029B ON agency_subscriptions (plan_id)');
        $this->addSql('CREATE TABLE invoices (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, invoice_number VARCHAR(50) NOT NULL, amount NUMERIC(10, 2) NOT NULL, tax_amount NUMERIC(10, 2) DEFAULT 0 NOT NULL, total_amount NUMERIC(10, 2) NOT NULL, pdf_url VARCHAR(500) DEFAULT NULL, status VARCHAR(255) NOT NULL, due_date DATE DEFAULT NULL, paid_date DATE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, agency_id INT NOT NULL, subscription_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_6A2F2F952DA68207 ON invoices (invoice_number)');
        $this->addSql('CREATE INDEX IDX_6A2F2F95CDEADB2A ON invoices (agency_id)');
        $this->addSql('CREATE INDEX IDX_6A2F2F959A1887DC ON invoices (subscription_id)');
        $this->addSql('CREATE TABLE payments (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, amount NUMERIC(10, 2) NOT NULL, currency VARCHAR(3) DEFAULT \'EUR\' NOT NULL, payment_method VARCHAR(255) NOT NULL, status VARCHAR(255) NOT NULL, stripe_payment_intent_id VARCHAR(255) DEFAULT NULL, invoice_url VARCHAR(500) DEFAULT NULL, paid_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, subscription_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_65D29B329A1887DC ON payments (subscription_id)');
        $this->addSql('CREATE TABLE subscription_plans (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, description TEXT DEFAULT NULL, price_monthly NUMERIC(10, 2) NOT NULL, price_yearly NUMERIC(10, 2) DEFAULT NULL, max_listings INT DEFAULT NULL, max_agents INT DEFAULT 1 NOT NULL, features JSON DEFAULT NULL, is_active BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE agency_subscriptions ADD CONSTRAINT FK_4FCF00D0CDEADB2A FOREIGN KEY (agency_id) REFERENCES agencies (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE agency_subscriptions ADD CONSTRAINT FK_4FCF00D0E899029B FOREIGN KEY (plan_id) REFERENCES subscription_plans (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE invoices ADD CONSTRAINT FK_6A2F2F95CDEADB2A FOREIGN KEY (agency_id) REFERENCES agencies (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE invoices ADD CONSTRAINT FK_6A2F2F959A1887DC FOREIGN KEY (subscription_id) REFERENCES agency_subscriptions (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE payments ADD CONSTRAINT FK_65D29B329A1887DC FOREIGN KEY (subscription_id) REFERENCES agency_subscriptions (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE agency_subscriptions DROP CONSTRAINT FK_4FCF00D0CDEADB2A');
        $this->addSql('ALTER TABLE agency_subscriptions DROP CONSTRAINT FK_4FCF00D0E899029B');
        $this->addSql('ALTER TABLE invoices DROP CONSTRAINT FK_6A2F2F95CDEADB2A');
        $this->addSql('ALTER TABLE invoices DROP CONSTRAINT FK_6A2F2F959A1887DC');
        $this->addSql('ALTER TABLE payments DROP CONSTRAINT FK_65D29B329A1887DC');
        $this->addSql('DROP TABLE agency_subscriptions');
        $this->addSql('DROP TABLE invoices');
        $this->addSql('DROP TABLE payments');
        $this->addSql('DROP TABLE subscription_plans');
    }
}
